# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='user', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='url',
            field=models.URLField(default='http://www.example.com/'),
            preserve_default=False,
        ),
    ]
