# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160519_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='body_html',
        ),
        migrations.AddField(
            model_name='post',
            name='body_markdown',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
