# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 07:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160613_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='timestamp',
            new_name='creation_time',
        ),
        migrations.AddField(
            model_name='post',
            name='modification_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 11, 7, 12, 57, 207949, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='blog.Category'),
        ),
    ]
